title: FFT-Analysator
description: Dieses Softwaremodul ist ein Werkzeug, um diverse Berechnungen zweier Signale im Bereich der Akustik auszuf√ºhren. 
theme: just-the-docs

url: https://kalleculated.github.io/FFT-Analysator/

aux_links:
  FFT-Analysator Repository: https://github.com/Kalleculated/FFT-Analysator
